# Generated by Django 5.1.6 on 2025-04-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='business_covers/'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
