# Generated by Django 5.1.6 on 2025-04-30 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesshours',
            old_name='close_time',
            new_name='closing_time',
        ),
        migrations.RenameField(
            model_name='businesshours',
            old_name='open_time',
            new_name='opening_time',
        ),
        migrations.RemoveField(
            model_name='review',
            name='business',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service'),
            preserve_default=False,
        ),
    ]
