# Generated by Django 5.1.6 on 2025-04-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_close_time_businesshours_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='has_discount',
            field=models.BooleanField(default=False),
        ),
    ]
